## 问题
给一个接口函数加上了try,catch 仍然会报错，无法捕捉到错误

## 解释
因为接口返回的是promise，是异步的操作，所以在同步函数中的try，catch无法捕捉异步的错误，需要将函数也改为异步

## 代码
```dsx
const markRead = async (id?: number) => {
    if (!(id || id === 0)) {
      return;
    }
    onHandleOpenChange?.(false);
    try {
      await markNoticeRead(id);
    } catch (err) {
      console.log(err);
    }
  };
```


